# Generated by Django 4.0.5 on 2022-06-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='value',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='type',
            field=models.CharField(choices=[(1, 'Rating'), (2, 'Mcq'), (3, 'Ranking'), (4, 'Value Based')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
