# Generated by Django 4.0.5 on 2022-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_surveyquestion_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='type',
            field=models.CharField(choices=[('1', 'Rating'), ('2', 'Mcq'), ('3', 'Ranking'), ('4', 'Value Based')], max_length=50),
        ),
    ]
