# Generated by Django 4.0.5 on 2022-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_survey_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredUserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='userEmail',
        ),
        migrations.AddField(
            model_name='survey',
            name='userEmail',
            field=models.ManyToManyField(blank=True, to='app.unregistereduseremail'),
        ),
    ]
